version: "3.9"

services:
  laravel:
    build:
      context: .                          # cartella contenente il Dockerfile
      dockerfile: docker/src/Dockerfile   # path relativo al Dockerfile
    container_name: laravel-app
    # volumes:
    #   - ./src:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - mysql_network

  nginx:
    build:
      context: .                          # cartella contenente il Dockerfile
      dockerfile: docker/nginx/Dockerfile  # path relativo al Dockerfile
    container_name: laravel-nginx
    ports:
      - "8888:80"
    # volumes:
    #   - ./docker/nginx/:/etc/nginx/conf.d/:ro
    depends_on:
      - laravel
    networks:
      - mysql_network

networks:
  mysql_network:
    external: true
    name: mysql_network
