version: "3.9"

services:
  laravel:
    build:
      context: ./src           # cartella contenente Laravel
      dockerfile: ./docker/Dockerfile   # path relativo al Dockerfile
    container_name: laravel-app
    volumes:
      - ./src:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: ${APP_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - mysql_network

  nginx:
    image: nginx:1.27
    container_name: laravel-nginx
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/:ro   # monta tutta la cartella
    depends_on:
      - laravel
    networks:
      - mysql_network

networks:
  mysql_network:
    external: true
    name: mysql_network
